DEFINT A-Z
DECLARE FUNCTION BSEARCH(A() AS DOUBLE, L AS INTEGER, TARGET AS DOUBLE)
DIM ARRAY(4096) AS DOUBLE : LENGTH = 0

REM READ DATA
F$ = "bsearch.csv"
OPEN F$ FOR INPUT AS #1
WHILE NOT EOF(1)
  INPUT #1,ARRAY(LENGTH)
  LENGTH = LENGTH + 1
  IF LENGTH > 2 THEN
    IF ARRAY(LENGTH-1) < ARRAY(LENGTH-2) THEN
      PRINT "Data not in ascending order."
      END
    END IF
  END IF
WEND
CLOSE #1

FOR I = 0 TO LENGTH-1
  RES = BSEARCH(ARRAY(), LENGTH, ARRAY(I))
  IF RES <> I THEN
    PRINT LENGTH; ARRAY(I); I; RES
  END IF
NEXT I
LENGTH = LENGTH - 1
FOR I = 0 TO LENGTH-1
  RES = BSEARCH(ARRAY(), LENGTH, ARRAY(I))
  IF RES <> I THEN
    PRINT LENGTH; ARRAY(I); I; RES
  END IF
NEXT I
END

FUNCTION BSEARCH(A() AS DOUBLE, L AS INTEGER, TARGET AS DOUBLE)
  LOW = 0 : HIGH = L-1
  WHILE LOW <= HIGH
    MID = INT((HIGH + LOW) / 2)
    IF A(MID) = TARGET THEN
      BSEARCH = MID : EXIT FUNCTION
    ELSEIF A(MID) < TARGET THEN
      LOW = MID + 1
    ELSE
      HIGH = MID - 1
    END IF
  WEND
  BSEARCH = -1
END FUNCTION