DEFINT A-Z
DECLARE SUB QSORT(A() AS DOUBLE, L AS INTEGER, R AS INTEGER)
DECLARE SUB BSORT(A() AS DOUBLE, L AS INTEGER, R AS INTEGER)

DIM ARRAY(4096) AS DOUBLE
COMMON LENGTH : LENGTH = 0

REM READ DATA FROM CSV

LENGTH = 888

RANDOMIZE TIMER
FOR I = 0 TO LENGTH-1
  ARRAY(I) = RND * 100
NEXT I
T# = TIMER
CALL QSORT(ARRAY(), 0, LENGTH-1)
PRINT TIMER - T#

SUB QSORT(A() AS DOUBLE, L AS INTEGER, R AS INTEGER)
  IF L >= R THEN EXIT SUB
  
  REM CHECK IF SEQ IS SORTED
  SORTED = 1
  FOR I = 0 TO R-1
    IF A(I) > A(I+1) THEN
      SORTED = 0
      EXIT FOR
    END IF
  NEXT I
  IF SORTED = 1 THEN EXIT SUB
  
  REM QUICK SORT MAIN
  I = L : J = R : K# = A(L)
  WHILE I < J
    WHILE I < J AND K# <= A(J)
      J = J - 1
    WEND
    A(I) = A(J)
    WHILE I < J AND K# >= A(I)
      I = I + 1
    WEND
    A(J) = A(I)
  WEND
  A(I) = K#
  
  REM QSORT FOR SUBGROUPS
  CALL QSORT(A(), L, I-1)
  CALL QSORT(A(), I+1, R)
END SUB

SUB BSORT(A() AS DOUBLE, L AS INTEGER, R AS INTEGER)
  FOR I=R TO L STEP -1:FOR J=L TO I-1
    IF A(J)>A(J+1) THEN
      T#=A(J):A(J)=A(J+1):A(J+1)=T#
    END IF
  NEXT J:NEXT I
END SUB
