port=2333
host="0.0.0.0"
max_connection=10
login_timeout=120
log_file="ssh.log"
log_level="DEBUG"

[[servers]]
username="frank"
host="127.0.0.1"
port=22
term="ansi.sys"

[[servers]]
username="termux"
remote_username="frank"
host="127.0.0.1"
port=8022
term="ansi"

