DEFINT A-Z
DIM SHARED N(4) AS INTEGER,P(24,4) AS INTEGER,M(127,99) AS INTEGER
DIM SHARED BM(16) AS INTEGER,HASH(2401) AS INTEGER,ASM(255) AS INTEGER
COMMON SHARED FRES$,GOALMAX,PL,IP,IDX,IDXMAX,SEGM,PTRM
SEGM=VARSEG(M(0,0)):PTRM=VARPTR(M(0,0))
FRES$="24STAT.CSV"
NMAX=13:IDXMAX=1820:GOALMAX=99:IDX=0:IP=0:PL=0
FOR I=0 TO 14:BM(I)=2^I:NEXT I:BM(15)=&H8000
FOR I=0 TO 3:N(I)=1:FOR J=0 TO 3
  IF I<>J THEN
    FOR K=0 TO 3
      IF I<>K AND J<>K THEN
        P(PL,0)=I:P(PL,1)=J:P(PL,2)=K:P(PL,3)=6-I-J-K
	PL=PL+1
      END IF
    NEXT K
  END IF
NEXT J:NEXT I

DEF SEG=VARSEG(ASM(0)):BLOAD "24STAT.BIN",VARPTR(ASM(0)):DEF SEG

PRINT USING "Processed: ####/#### ###.#%  ";IDX,IDXMAX,CDBL(IDX)*100/IDXMAX;
MOF=VARPTR(M(IDX\16,0)):MMASK=BM(IDX AND 15)
T0#=TIMER
WHILE N(0)<=NMAX
  CALL CALC24(N(),IP,MOF,MMASK)
  IP=IP+1
  IF IP>=PL THEN
    CALL CLEARHASH
    N(3)=N(3)+1
    IF N(3)>NMAX THEN
      N(2)=N(2)+1
      IF N(2)>NMAX THEN
        N(1)=N(1)+1
        IF N(1)>NMAX THEN
          N(0)=N(0)+1
          N(1)=N(0)
        END IF
        N(2)=N(1)
      END IF
      N(3)=N(2)
    END IF
    IP=0
    IDX=IDX+1
    MOF=VARPTR(M(IDX\16,0)):MMASK=BM(IDX AND 15)
    LOCATE ,1
    PRINT USING "Processed: ####/#### ###.#%  ";IDX,IDXMAX,CDBL(IDX)*100/IDXMAX;
  END IF
WEND
PRINT "":PRINT "Writing ";FRES$;
OPEN FRES$ FOR OUTPUT AS #1
PRINT #1,"Goal,Solvable In "+LTRIM$(RTRIM$(STR$(IDXMAX)))
FOR G=0 TO GOALMAX
  PRINT #1,LTRIM$(RTRIM$(STR$(G)));",";LTRIM$(RTRIM$(STR$(COUNTRES(G))))
NEXT G
CLOSE #1
PRINT " Done."
END

SUB CALC24(N() AS INTEGER,I AS INTEGER,OF AS INTEGER,MASK AS INTEGER):
  STATIC A AS INTEGER,B AS INTEGER,C AS INTEGER,D AS INTEGER
  A=N(P(I,0)):B=N(P(I,1)):C=N(P(I,2)):D=N(P(I,3))
  IF PROCHASH(A,B,C,D)=0 THEN EXIT SUB
  DEF SEG=VARSEG(ASM(0))
  CALL ABSOLUTE(BYVAL A,BYVAL B,BYVAL C,BYVAL D,BYVAL MASK,BYVAL OF,BYVAL VARSEG(M(0,0)),VARPTR(ASM(0)))
  DEF SEG
END SUB

FUNCTION COUNTRES(G AS INTEGER)
  DIM BM AS INTEGER
  N=0
  FOR I=0 TO 114
    BM=M(I,G)
    IF (BM AND &H8000)<>0 THEN N=N+1:BM=BM AND &H7FFF
    WHILE BM>0
      BM=BM AND (BM-1):N=N+1
    WEND
  NEXT I
  COUNTRES=N
END FUNCTION

SUB CLEARHASH
  FOR I=0 TO 2400:HASH(I)=0:NEXT I
END SUB

FUNCTION PROCHASH(A AS INTEGER,B AS INTEGER,C AS INTEGER,D AS INTEGER)
  STATIC D0 AS INTEGER,D1 AS INTEGER,D2 AS INTEGER,RES AS INTEGER
  STATIC HS AS INTEGER,MHASH AS INTEGER
  D0=B-A+15:D1=C-B+15:D2=D-C+15
  HS=D2+D1*32+D0*1024:MHASH=BM(D2 AND 15):HS=HS\16
  IF (HASH(HS) AND MHASH)<>0 THEN
    RES=0
  ELSE
    RES=1:HASH(HS)=HASH(HS) OR MHASH
  END IF
  PROCHASH=RES
END FUNCTION

